/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesar;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class login_page extends javax.swing.JFrame {

    /**
     * Creates new form login_page
     */
    public login_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pane_login = new javax.swing.JTabbedPane();
        welcome_page = new javax.swing.JPanel();
        title_welcome = new javax.swing.JPanel();
        txt_welcome = new javax.swing.JLabel();
        title_select = new javax.swing.JLabel();
        panelRound1 = new tugasbesar.PanelRound();
        btn_admin = new tugasbesar.ButtonRound();
        btn_user = new tugasbesar.ButtonRound();
        login_admin = new javax.swing.JPanel();
        panel_admin = new javax.swing.JPanel();
        title_admin = new javax.swing.JLabel();
        buttonRound1 = new tugasbesar.ButtonRound();
        panel_admin_login = new javax.swing.JPanel();
        panelRound5 = new tugasbesar.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        show_password_admin = new javax.swing.JCheckBox();
        password_admin = new tugasbesar.FPasswordField();
        username_admin = new tugasbesar.TextFieldRound();
        btn_login_admin = new tugasbesar.ButtonRound();
        jLabel4 = new javax.swing.JLabel();
        login_user = new javax.swing.JPanel();
        panel_user = new javax.swing.JPanel();
        title_admin1 = new javax.swing.JLabel();
        buttonRound2 = new tugasbesar.ButtonRound();
        panel_user_login = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelRound6 = new tugasbesar.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        show_password_user = new javax.swing.JCheckBox();
        password_user = new tugasbesar.FPasswordField();
        username_user = new tugasbesar.TextFieldRound();
        btn_login_user = new tugasbesar.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(22, 25, 32));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_page.setBackground(new java.awt.Color(22, 25, 32));

        title_welcome.setBackground(new java.awt.Color(0, 0, 0));

        txt_welcome.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        txt_welcome.setForeground(new java.awt.Color(255, 255, 255));
        txt_welcome.setText("WELCOME");

        javax.swing.GroupLayout title_welcomeLayout = new javax.swing.GroupLayout(title_welcome);
        title_welcome.setLayout(title_welcomeLayout);
        title_welcomeLayout.setHorizontalGroup(
            title_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_welcomeLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(txt_welcome)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        title_welcomeLayout.setVerticalGroup(
            title_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_welcomeLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(txt_welcome)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        title_select.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        title_select.setForeground(new java.awt.Color(255, 255, 255));
        title_select.setText("PLEASE SELECT");

        panelRound1.setBackground(new java.awt.Color(32, 49, 59));
        panelRound1.setRoundBottomLeft(15);
        panelRound1.setRoundBottomRight(15);
        panelRound1.setRoundTopLeft(15);
        panelRound1.setRoundTopRight(15);

        btn_admin.setBackground(new java.awt.Color(0, 96, 213));
        btn_admin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_admin.setForeground(new java.awt.Color(255, 255, 255));
        btn_admin.setText("ADMIN");
        btn_admin.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btn_admin.setRoundBottomLeft(15);
        btn_admin.setRoundBottomRight(15);
        btn_admin.setRoundTopLeft(15);
        btn_admin.setRoundTopRight(15);
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });

        btn_user.setBackground(new java.awt.Color(0, 96, 213));
        btn_user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_user.setText("USER");
        btn_user.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btn_user.setRoundBottomLeft(15);
        btn_user.setRoundBottomRight(15);
        btn_user.setRoundTopLeft(15);
        btn_user.setRoundTopRight(15);
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout welcome_pageLayout = new javax.swing.GroupLayout(welcome_page);
        welcome_page.setLayout(welcome_pageLayout);
        welcome_pageLayout.setHorizontalGroup(
            welcome_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_pageLayout.createSequentialGroup()
                .addComponent(title_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(welcome_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcome_pageLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(title_select))
                    .addGroup(welcome_pageLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        welcome_pageLayout.setVerticalGroup(
            welcome_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(welcome_pageLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(title_select)
                .addGap(18, 18, 18)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pane_login.addTab("tab1", welcome_page);

        login_admin.setBackground(new java.awt.Color(22, 25, 32));

        panel_admin.setBackground(new java.awt.Color(0, 0, 0));

        title_admin.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        title_admin.setForeground(new java.awt.Color(255, 255, 255));
        title_admin.setText("ADMIN");

        buttonRound1.setBackground(new java.awt.Color(255, 255, 255));
        buttonRound1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonRound1.setForeground(new java.awt.Color(0, 0, 0));
        buttonRound1.setText("BACK");
        buttonRound1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        buttonRound1.setRoundBottomLeft(15);
        buttonRound1.setRoundBottomRight(15);
        buttonRound1.setRoundTopLeft(15);
        buttonRound1.setRoundTopRight(15);
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_adminLayout = new javax.swing.GroupLayout(panel_admin);
        panel_admin.setLayout(panel_adminLayout);
        panel_adminLayout.setHorizontalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addGroup(panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(title_admin))
                    .addGroup(panel_adminLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panel_adminLayout.setVerticalGroup(
            panel_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223)
                .addComponent(title_admin)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        panel_admin_login.setBackground(new java.awt.Color(22, 25, 32));

        panelRound5.setBackground(new java.awt.Color(32, 49, 69));
        panelRound5.setRoundBottomLeft(15);
        panelRound5.setRoundBottomRight(15);
        panelRound5.setRoundTopLeft(15);
        panelRound5.setRoundTopRight(15);

        jLabel1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 175, 244));
        jLabel1.setText("USERNAME");

        jLabel2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 175, 244));
        jLabel2.setText("PASSWORD");

        show_password_admin.setBackground(new java.awt.Color(32, 49, 69));
        show_password_admin.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        show_password_admin.setForeground(new java.awt.Color(255, 255, 255));
        show_password_admin.setText("Show Password");
        show_password_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_adminActionPerformed(evt);
            }
        });

        password_admin.setBackground(new java.awt.Color(255, 255, 255));
        password_admin.setForeground(new java.awt.Color(0, 0, 0));
        password_admin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        password_admin.setRoundBottomLeft(15);
        password_admin.setRoundBottomRight(15);
        password_admin.setRoundTopLeft(15);
        password_admin.setRoundTopRight(15);

        username_admin.setBackground(new java.awt.Color(255, 255, 255));
        username_admin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        username_admin.setForeground(new java.awt.Color(0, 0, 0));
        username_admin.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        username_admin.setRoundBottomLeft(15);
        username_admin.setRoundBottomRight(15);
        username_admin.setRoundTopLeft(15);
        username_admin.setRoundTopRight(15);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(password_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(show_password_admin, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound5Layout.createSequentialGroup()
                            .addGroup(panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show_password_admin)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_login_admin.setBackground(new java.awt.Color(0, 96, 213));
        btn_login_admin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_login_admin.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_admin.setText("LOGIN");
        btn_login_admin.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btn_login_admin.setRoundBottomLeft(15);
        btn_login_admin.setRoundBottomRight(15);
        btn_login_admin.setRoundTopLeft(15);
        btn_login_admin.setRoundTopRight(15);
        btn_login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_adminActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN");

        javax.swing.GroupLayout panel_admin_loginLayout = new javax.swing.GroupLayout(panel_admin_login);
        panel_admin_login.setLayout(panel_admin_loginLayout);
        panel_admin_loginLayout.setHorizontalGroup(
            panel_admin_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_admin_loginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_admin_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_admin_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_admin_loginLayout.createSequentialGroup()
                        .addComponent(btn_login_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_admin_loginLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(176, 176, 176))))
        );
        panel_admin_loginLayout.setVerticalGroup(
            panel_admin_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_admin_loginLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btn_login_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout login_adminLayout = new javax.swing.GroupLayout(login_admin);
        login_admin.setLayout(login_adminLayout);
        login_adminLayout.setHorizontalGroup(
            login_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_adminLayout.createSequentialGroup()
                .addComponent(panel_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(panel_admin_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        login_adminLayout.setVerticalGroup(
            login_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_admin_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pane_login.addTab("tab2", login_admin);

        login_user.setBackground(new java.awt.Color(255, 255, 255));
        login_user.setForeground(new java.awt.Color(0, 0, 0));

        panel_user.setBackground(new java.awt.Color(0, 0, 0));

        title_admin1.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        title_admin1.setForeground(new java.awt.Color(255, 255, 255));
        title_admin1.setText("USER");

        buttonRound2.setBackground(new java.awt.Color(255, 255, 255));
        buttonRound2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonRound2.setForeground(new java.awt.Color(0, 0, 0));
        buttonRound2.setText("BACK");
        buttonRound2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        buttonRound2.setRoundBottomLeft(15);
        buttonRound2.setRoundBottomRight(15);
        buttonRound2.setRoundTopLeft(15);
        buttonRound2.setRoundTopRight(15);
        buttonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_userLayout = new javax.swing.GroupLayout(panel_user);
        panel_user.setLayout(panel_userLayout);
        panel_userLayout.setHorizontalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_userLayout.createSequentialGroup()
                .addGroup(panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_userLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(title_admin1))
                    .addGroup(panel_userLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        panel_userLayout.setVerticalGroup(
            panel_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223)
                .addComponent(title_admin1)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        panel_user_login.setBackground(new java.awt.Color(22, 25, 32));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGIN");

        panelRound6.setBackground(new java.awt.Color(32, 49, 69));
        panelRound6.setRoundBottomLeft(15);
        panelRound6.setRoundBottomRight(15);
        panelRound6.setRoundTopLeft(15);
        panelRound6.setRoundTopRight(15);

        jLabel3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 175, 244));
        jLabel3.setText("USERNAME");

        jLabel8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(4, 175, 244));
        jLabel8.setText("PASSWORD");

        show_password_user.setBackground(new java.awt.Color(32, 49, 69));
        show_password_user.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        show_password_user.setForeground(new java.awt.Color(255, 255, 255));
        show_password_user.setText("Show Password");
        show_password_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_userActionPerformed(evt);
            }
        });

        password_user.setBackground(new java.awt.Color(255, 255, 255));
        password_user.setForeground(new java.awt.Color(0, 0, 0));
        password_user.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        password_user.setRoundBottomLeft(15);
        password_user.setRoundBottomRight(15);
        password_user.setRoundTopLeft(15);
        password_user.setRoundTopRight(15);

        username_user.setBackground(new java.awt.Color(255, 255, 255));
        username_user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        username_user.setForeground(new java.awt.Color(0, 0, 0));
        username_user.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        username_user.setRoundBottomLeft(15);
        username_user.setRoundBottomRight(15);
        username_user.setRoundTopLeft(15);
        username_user.setRoundTopRight(15);

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_user, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(password_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_password_user, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound6Layout.createSequentialGroup()
                        .addGroup(panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_user, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_user, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(show_password_user)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btn_login_user.setBackground(new java.awt.Color(0, 96, 213));
        btn_login_user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_login_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_login_user.setText("LOGIN");
        btn_login_user.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btn_login_user.setRoundBottomLeft(15);
        btn_login_user.setRoundBottomRight(15);
        btn_login_user.setRoundTopLeft(15);
        btn_login_user.setRoundTopRight(15);
        btn_login_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_user_loginLayout = new javax.swing.GroupLayout(panel_user_login);
        panel_user_login.setLayout(panel_user_loginLayout);
        panel_user_loginLayout.setHorizontalGroup(
            panel_user_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_user_loginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_user_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_user_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_user_loginLayout.createSequentialGroup()
                        .addComponent(btn_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_user_loginLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(176, 176, 176))))
        );
        panel_user_loginLayout.setVerticalGroup(
            panel_user_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_user_loginLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addComponent(panelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btn_login_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout login_userLayout = new javax.swing.GroupLayout(login_user);
        login_user.setLayout(login_userLayout);
        login_userLayout.setHorizontalGroup(
            login_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_userLayout.createSequentialGroup()
                .addComponent(panel_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(panel_user_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        login_userLayout.setVerticalGroup(
            login_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_user_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pane_login.addTab("tab3", login_user);

        jPanel3.add(pane_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 950, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(964, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        // TODO add your handling code here:
        pane_login.setSelectedIndex(1);
    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        // TODO add your handling code here:
        pane_login.setSelectedIndex(2);
    }//GEN-LAST:event_btn_userActionPerformed

    private void show_password_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_adminActionPerformed
        // TODO add your handling code here:
        if(show_password_admin.isSelected()){
            password_admin.setEchoChar((char)0);
        }
        else{
            password_admin.setEchoChar('*');
        }
    }//GEN-LAST:event_show_password_adminActionPerformed

    private void btn_login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_adminActionPerformed
        // TODO add your handling code here:
        if(username_admin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out username");
        }
        else if(password_admin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out password");
        }
        else if(username_admin.getText().contains("Faris")&& password_admin.getText().contains("faris"))
        {
            gameStore game = new gameStore();
            game.setVisible(true);

            this.setVisible(false);
        }
        else if(username_admin.getText().contains("Rashad")&& password_admin.getText().contains("rashad"))
        {
            gameStore game = new gameStore();
            game.setVisible(true);

            this.setVisible(false);
        }
        else if(username_admin.getText().contains("Raihan")&& password_admin.getText().contains("raihan"))
        {
            gameStore game = new gameStore();
            game.setVisible(true);

            this.setVisible(false);
        }
        else if(username_admin.getText().contains("Rama")&& password_admin.getText().contains("rama"))
        {
            gameStore game = new gameStore();
            game.setVisible(true);

            this.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong username or password!!!",
                    "Message",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_login_adminActionPerformed

    private void show_password_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_userActionPerformed
        // TODO add your handling code here:
        if(show_password_user.isSelected()){
            password_user.setEchoChar((char)0);
        }
        else{
            password_user.setEchoChar('*');
        }
    
    }//GEN-LAST:event_show_password_userActionPerformed

    private void btn_login_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_userActionPerformed
        // TODO add your handling code here:
        if(username_user.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out username");
        }
        else if(password_user.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out password");
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong username or password!!!",
                    "Message",JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btn_login_userActionPerformed

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
        // TODO add your handling code here:
        pane_login.setSelectedIndex(0);
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void buttonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound2ActionPerformed
        // TODO add your handling code here:
        pane_login.setSelectedIndex(0);
    }//GEN-LAST:event_buttonRound2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tugasbesar.ButtonRound btn_admin;
    private tugasbesar.ButtonRound btn_login_admin;
    private tugasbesar.ButtonRound btn_login_user;
    private tugasbesar.ButtonRound btn_user;
    private tugasbesar.ButtonRound buttonRound1;
    private tugasbesar.ButtonRound buttonRound2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login_admin;
    private javax.swing.JPanel login_user;
    private javax.swing.JTabbedPane pane_login;
    private tugasbesar.PanelRound panelRound1;
    private tugasbesar.PanelRound panelRound5;
    private tugasbesar.PanelRound panelRound6;
    private javax.swing.JPanel panel_admin;
    private javax.swing.JPanel panel_admin_login;
    private javax.swing.JPanel panel_user;
    private javax.swing.JPanel panel_user_login;
    private tugasbesar.FPasswordField password_admin;
    private tugasbesar.FPasswordField password_user;
    private javax.swing.JCheckBox show_password_admin;
    private javax.swing.JCheckBox show_password_user;
    private javax.swing.JLabel title_admin;
    private javax.swing.JLabel title_admin1;
    private javax.swing.JLabel title_select;
    private javax.swing.JPanel title_welcome;
    private javax.swing.JLabel txt_welcome;
    private tugasbesar.TextFieldRound username_admin;
    private tugasbesar.TextFieldRound username_user;
    private javax.swing.JPanel welcome_page;
    // End of variables declaration//GEN-END:variables
}
